FROM gorzechowski/{{image}}

RUN apt-get -y update && apt-get -qy install \
    libfcgi-dev

RUN groupadd hetach && \
    useradd -g hetach -s /bin/bash hetach

COPY . /opt/hetach

RUN chown -R hetach:hetach /opt/hetach

USER hetach
